name: techfix_pro
description: TechFix Pro - Repair Shop Management System
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  image_picker: ^1.1.2        # Camera + gallery picker
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2        # For local file paths
  permission_handler: ^11.3.0  # Camera/storage permissions
  cached_network_image: ^3.3.1 # Display captured images
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  firebase_database: ^12.1.3
  firebase_storage: ^13.0.6
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
